apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-frontend
  labels:
    app: taskflow-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskflow-frontend
  template:
    metadata:
      labels:
        app: taskflow-frontend
    spec:
      containers:
      - name: taskflow-frontend
        image: cloudnativeproject-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: taskflow-frontend-service
spec:
  selector:
    app: taskflow-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
